version: '3.1'
services:
  db:
    image: mysql
    container_name: qyon_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - qyon_data:/var/lib/mysql

volumes:
  qyon_data: